server:
  port: 8001

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://rep.360taihe.com/hzcyn/config-repo.git
          search-paths: '{application}'
          username:
          password: