server:
  port: 8001

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://rep.360taihe.com/scm-group/scm-purchase-cloud.git
          search-paths: /*/*
          username: hzcyn
          password: hzcyn233