server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xmn1986/springCloudConfig.git
          search-paths: respo
          username: xmn1986
          password: wdx123456
      label: master


eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:123456@localhost:8000/eureka/

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin