spring:
  application:
    name: registry
  profiles:
    active: dev

server:
  port: 8000

security:
  basic:
    enabled: true
  user:
    name: registry
    password: 123456

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://registry:123456@localhost:${server.port}/eureka