spring:
  redis:
    host: 10.200.131.78
    port: 6379
    password: open123wlg
    adtabase: 5
  datasource:
    url: jdbc:mysql://10.200.131.78:3306/purchase?characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
    username: root
    password: 20170104lws